language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  apt:
    packages:
      - php5-ldap

before_install:
  - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - mysql -e 'create database klio;'

install:
  - composer install
  - echo "<?php \$database_test = array('database'=>'klio','username'=>'root','password'=>'','hostname'=>'localhost');" > $TRAVIS_BUILD_DIR/settings.php

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs --report=full --standard=PSR2 modules/*/classes modules/*/tests
