language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/phpcs.sh

before_script:
  - mysql -e 'create database klio_test;'

install:
  - composer install
  - echo "<?php \$database_config = array('database'=>'klio','username'=>'root','password'=>'');" >> $TRAVIS_BUILD_DIR/config.php
